# 04장 Numpy 통계학
- 행렬과 선형대수

In [2]:
import numpy as np
import pandas as pd
from numpy.random import seed
from numpy.random import rand
from numpy.random import randint
seed(42)
# seed 를 고정시켜야 rand 로 돌려도 rand 의 값이 고정된다. 따라서 데이터를 분석할 때 seed를 고정시켜놓고 한다.
# 만약 고정하지 않고 돌린다면, 데이터를 분석하는 사람들 사이에서 시간의 차이가 발생할 수 있다.
# rand(7)
# np.random.seed(42)
# np.random.rand(n) # 0과 1 사이의 값을 균일분포로 난수 n개 생성
# np.random.randint(start, end + 1, size)
# randint(1, 9, 3) array([4, 7, 4])

In [7]:
a = np.arange(12).reshape(3,4)

# Numpy 통계함수
print(a.sum())
print(a.mean())
print(a.std())
print(a.max())
print(a.min())

from scipy.stats import scoreatpercentile
print(scoreatpercentile(a, 50))   # 중간값, a = 행렬, 50 = %  # a 중 50%에 해당하는 값

print(np.zeros(10))
print(np.zeros((3,4)))
print(np.ones(5))
print(np.ones((3,5)))

66
5.5
3.452052529534663
11
0
5.5
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [13]:
# 행렬과 선형대수
A = np.mat("2 4 6;4 2 6;10 -4 18")
print(A,type(A)) # <class 'numpy.matrix'>
# [[ 2  4  6]
#  [ 4  2  6]
#  [10 -4 18]]


# 역행렬  :  A * X = E (E:항등행렬, 왼쪽 위에서 대각선으로 1, 나머지는 0) 항등행렬 : 어떤 값을 곱해도 원본 그대로로 만들어주는 행렬
# 역행렬 A * A^-1 = E , A^-1 * A = E (A와 A^-1은 역행렬 관계)

inverse = np.linalg.inv(A)
print(inverse)

E = A * inverse
print(E)

[[ 2  4  6]
 [ 4  2  6]
 [10 -4 18]] <class 'numpy.matrix'>
[[-0.41666667  0.66666667 -0.08333333]
 [ 0.08333333  0.16666667 -0.08333333]
 [ 0.25       -0.33333333  0.08333333]]
[[ 1.00000000e+00 -2.22044605e-16  0.00000000e+00]
 [ 5.55111512e-17  1.00000000e+00  0.00000000e+00]
 [ 3.88578059e-16 -4.44089210e-16  1.00000000e+00]]


In [29]:
# 선형방정식
A = np.mat("1 -2 1;0 2 -8;-4 5 9")
A
B = np.array([0,8,-9])

print(A)
print(B)
# 1*X0 - 2*X1 + 1*2X = 0
# 0*X0 + 2X1 - 8X2 = 8
# -4*X0 + 5*X1 +9*X2 = -9

x = np.linalg.solve(A, B)
print(x) # [29. 16.  3.]
print(np.dot(A, x)) # [ 0.  8. -9.] # A * x = B -> w*x = y
                                    # x = inverse_A * B   # x 구하는 방법
inverse = np.linalg.inv(A)
x = np.dot(inverse, B)
print('using inverse: ',x)

[[ 1 -2  1]
 [ 0  2 -8]
 [-4  5  9]]
[ 0  8 -9]
[29. 16.  3.]
[[ 0.  8. -9.]]
using inverse:  [[29. 16.  3.]]


In [27]:
a1 = np.arange(4).reshape(2,2)
a2 = np.arange(4).reshape(2,2)
print(a1)
print(a2)
print(a1*a2) # 안에 있는 요소간의 곱셈
print(np.dot(a1, a2)) # matrix 곱셈 , dot product 곱셈
# (m, n) * (n , l) = (m, l) -> 행렬의 shape
# 첫 행렬의 m = 행의 개수 n = 열의 개수


[[0 1]
 [2 3]]
[[0 1]
 [2 3]]
[[0 1]
 [4 9]]
[[ 2  3]
 [ 6 11]]
